spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: admin
    password: veref2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
